version: '3'

services:
        dbos:
                image: mysql:5.7
                restart: always
                environment:
                        MYSQL_ROOT_PASSWORD: root1425
                        MYSQL_USER: aayush
                        MYSQL_PASSWORD: DBpass13
                        MYSQL_DATABASE: examdb
                volumes:
                        - mysql_storage:/var/lib/mysql
        wpos:
                image: wordpress:5.1.1-php7.3-apache
                restart: always
                environment:
                        WORDPRESS_DB_HOST: dbos
                        WORDPRESS_DB_USER: aayush
                        WORDPRESS_DB_PASSWORD: DBpass13
                        WORDPRESS_DB_NAME: examdb
                depends_on:
                        - dbos
                ports:
                        - 1234:80
                volumes:
                        - wp_storage:/var/www/html

volumes:
        mysql_storage:
        wp_storage:
